name: BladeRunnerJS (BRJS) - Divide &amp; conquer complex web apps
pygments: true
relative_permalinks: false
permalink: /blog/:title

base_url: http://bladerunnerjs.org

exclude: [ node_modules ]

paginate: 7
paginate_path: "blog/page/:num"

markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]

social:
  twitter_link: https://twitter.com/BladeRunnerJS
  github_link: https://github.com/bladerunnerjs/brjs
  github_issues_link: https://github.com/bladerunnerjs/brjs/issues
  docs_issues_link: https://github.com/bladerunnerjs/brjs-site/issues
  so_question_link: http://stackoverflow.com/questions/ask?tags=BladeRunnerJS
  mailing_list_link: http://caplin.us7.list-manage.com/subscribe/?u=b11bf2689d15a7cdd68a0904a&amp;id=4649bf0c91

authors:
  leggetter:
    display_name: Phil Leggetter
    url: "https://github.com/leggetter"
    twitter: "leggetter"
    github: leggetter
    avatar: https://avatars2.githubusercontent.com/u/328367?s=460
    role: Dev Evangelist
  andyberry88:
    display_name: Andy Berry
    url: "https://github.com/andyberry88"
    twitter: "andyberry88"
    github: andyberry88
    avatar: https://avatars3.githubusercontent.com/u/726896?s=460
    role: Senior Software Engineer &amp; Tech Lead
  domc:
    display_name: Dom Chambers
    avatar: https://avatars0.githubusercontent.com/u/283294?s=460
    role: Senior Software Engineer
    github: dchambers
    url: "https://github.com/dchambers"
  sospirited:
    display_name: Pre Vyas
    url: "https://github.com/sospirited"
    github: sospirited
    avatar: https://avatars3.githubusercontent.com/u/1389953?s=460
    role: Senior QA Engineer
  jamest:
    display_name: James Turner
    avatar: https://avatars2.githubusercontent.com/u/5113519?s=460
    role: Caplin System Architect and BRJS Product "Owner"
    github: james-shaw-turner
    url: "https://github.com/james-shaw-turner"
  kybernetikos:
    display_name: Adam Iley
    avatar: https://avatars0.githubusercontent.com/u/430980?v=3&s=460
    role: Senior Software Engineer
    github: kybernetikos
    url: "https://github.com/kybernetikos"
  ioanalianabalas:
    display_name: Ioana Balas
    avatar: https://avatars1.githubusercontent.com/u/8642595?v=3&s=460
    url: "https://github.com/ioanalianabalas"
    github: ioanalianabalas
    role: Junior Software Engineer
  thanhc:
    display_name: Thanh Cam  
    avatar: https://avatars0.githubusercontent.com/u/5188693?v=3&s=460
    url: "https://github.com/thanhc"
    github: thanh
    role: QA Engineer
  thecapdan:
    display_name: Daniel Owen  
    avatar: https://avatars0.githubusercontent.com/u/6085260?v=3&s=460
    url: "https://github.com/thecapdan"
    github: thecapdan
    role: QA Engineer  
team: [ andyberry88, domc, jamest, ioanalianabalas, thanhc ]
other_contributors: [ leggetter, sospirited, thecapdan, kybernetikos ]