name: BladeRunnerJS - Divide &amp; conquer your web apps
pygments: true
relative_permalinks: false
permalink: /blog/:title

social:
  twitter_link: https://twitter.com/BladeRunnerJS
  github_link: https://github.com/bladerunnerjs/brjs
  github_issues_link: https://github.com/bladerunnerjs/brjs/issues
  mailing_list_link: http://caplin.us7.list-manage.com/subscribe/?u=b11bf2689d15a7cdd68a0904a&amp;id=4649bf0c91

authors:
  leggetter:
    display_name: Phil Leggetter
    twitter: "@leggetter"
    github: leggetter
    gravatar:
  jamest:
    display_name: James Turner